import { MatchFixture, OddsLine, TeamProfile } from '@/lib/types';

export const teams: TeamProfile[] = [
  {
    name: 'Arsenal',
    power: 87,
    homeAdvantage: 4,
    awayAdjustment: -1,
    form: 8,
    xgFor: 1.95,
    xgAgainst: 0.92,
    pressing: 8,
    buildUp: 9,
    transition: 7,
    setPieces: 8,
    crossing: 6,
    aerialDefense: 7,
  },
  {
    name: 'Liverpool',
    power: 89,
    homeAdvantage: 4,
    awayAdjustment: -1,
    form: 9,
    xgFor: 2.15,
    xgAgainst: 1.01,
    pressing: 9,
    buildUp: 8,
    transition: 9,
    setPieces: 7,
    crossing: 7,
    aerialDefense: 7,
  },
  {
    name: 'Manchester City',
    power: 91,
    homeAdvantage: 4,
    awayAdjustment: -1,
    form: 7,
    xgFor: 2.05,
    xgAgainst: 0.88,
    pressing: 8,
    buildUp: 10,
    transition: 7,
    setPieces: 7,
    crossing: 6,
    aerialDefense: 8,
  },
  {
    name: 'Newcastle',
    power: 81,
    homeAdvantage: 3,
    awayAdjustment: -1,
    form: 7,
    xgFor: 1.71,
    xgAgainst: 1.18,
    pressing: 8,
    buildUp: 6,
    transition: 8,
    setPieces: 7,
    crossing: 7,
    aerialDefense: 6,
  },
  {
    name: 'Brighton',
    power: 78,
    homeAdvantage: 3,
    awayAdjustment: -1,
    form: 6,
    xgFor: 1.58,
    xgAgainst: 1.34,
    pressing: 7,
    buildUp: 8,
    transition: 7,
    setPieces: 5,
    crossing: 6,
    aerialDefense: 5,
  },
  {
    name: 'Brentford',
    power: 74,
    homeAdvantage: 3,
    awayAdjustment: -1,
    form: 6,
    xgFor: 1.49,
    xgAgainst: 1.41,
    pressing: 6,
    buildUp: 5,
    transition: 8,
    setPieces: 8,
    crossing: 7,
    aerialDefense: 6,
  },
  {
    name: 'Tottenham',
    power: 79,
    homeAdvantage: 3,
    awayAdjustment: -1,
    form: 5,
    xgFor: 1.82,
    xgAgainst: 1.55,
    pressing: 8,
    buildUp: 7,
    transition: 8,
    setPieces: 5,
    crossing: 7,
    aerialDefense: 5,
  },
  {
    name: 'Aston Villa',
    power: 80,
    homeAdvantage: 3,
    awayAdjustment: -1,
    form: 7,
    xgFor: 1.69,
    xgAgainst: 1.21,
    pressing: 7,
    buildUp: 7,
    transition: 7,
    setPieces: 7,
    crossing: 6,
    aerialDefense: 6,
  }
];

export const fixtures: MatchFixture[] = [
  {
    id: 'gw34-ars-bre',
    round: 34,
    kickoff: '2026-04-25T14:00:00Z',
    homeTeam: 'Arsenal',
    awayTeam: 'Brentford',
    daysRestHome: 6,
    daysRestAway: 7,
    injuriesHome: 1,
    injuriesAway: 2,
  },
  {
    id: 'gw34-liv-bha',
    round: 34,
    kickoff: '2026-04-25T16:30:00Z',
    homeTeam: 'Liverpool',
    awayTeam: 'Brighton',
    daysRestHome: 5,
    daysRestAway: 6,
    injuriesHome: 1,
    injuriesAway: 2,
  },
  {
    id: 'gw34-mci-new',
    round: 34,
    kickoff: '2026-04-26T13:00:00Z',
    homeTeam: 'Manchester City',
    awayTeam: 'Newcastle',
    daysRestHome: 4,
    daysRestAway: 7,
    injuriesHome: 2,
    injuriesAway: 1,
  },
  {
    id: 'gw34-tot-avl',
    round: 34,
    kickoff: '2026-04-26T15:30:00Z',
    homeTeam: 'Tottenham',
    awayTeam: 'Aston Villa',
    daysRestHome: 6,
    daysRestAway: 5,
    injuriesHome: 3,
    injuriesAway: 1,
  }
];

export const latestOdds: OddsLine[] = [
  {
    fixtureId: 'gw34-ars-bre',
    bookmaker: 'MockBook',
    home: 1.52,
    draw: 4.35,
    away: 6.7,
    over2_5: 1.74,
    under2_5: 2.12,
    btts_yes: 1.82,
    btts_no: 1.97,
    capturedAt: '2026-04-22T08:00:00Z',
  },
  {
    fixtureId: 'gw34-liv-bha',
    bookmaker: 'MockBook',
    home: 1.7,
    draw: 4.1,
    away: 4.9,
    over2_5: 1.62,
    under2_5: 2.3,
    btts_yes: 1.71,
    btts_no: 2.08,
    capturedAt: '2026-04-22T08:00:00Z',
  },
  {
    fixtureId: 'gw34-mci-new',
    bookmaker: 'MockBook',
    home: 1.88,
    draw: 3.95,
    away: 4.0,
    over2_5: 1.68,
    under2_5: 2.2,
    btts_yes: 1.75,
    btts_no: 2.02,
    capturedAt: '2026-04-22T08:00:00Z',
  },
  {
    fixtureId: 'gw34-tot-avl',
    bookmaker: 'MockBook',
    home: 2.48,
    draw: 3.55,
    away: 2.8,
    over2_5: 1.66,
    under2_5: 2.25,
    btts_yes: 1.63,
    btts_no: 2.22,
    capturedAt: '2026-04-22T08:00:00Z',
  }
];

export type TrackerSeedPick = {
  fixtureId: string;
  kickoff: string;
  homeTeam: string;
  awayTeam: string;
  market: 'home' | 'draw' | 'away' | 'over2_5' | 'under2_5' | 'btts_yes' | 'btts_no';
  bookmakerOdds: number;
  modelProbability: number;
  expectedValue: number;
  confidence: number;
  note: string;
};

export type TrackerSeedResult = {
  fixtureId: string;
  homeGoals: number;
  awayGoals: number;
};

export const trackerSeedPicks: TrackerSeedPick[] = [
  {
    fixtureId: 'seed-bou-lee-20260422-away',
    kickoff: '2026-04-22T19:00:00Z',
    homeTeam: 'Bournemouth',
    awayTeam: 'Leeds United',
    market: 'away',
    bookmakerOdds: 5.5,
    modelProbability: 0.2009,
    expectedValue: 0.1049,
    confidence: 38.16,
    note: 'Seeded prior pick for tracker foundation',
  },
  {
    fixtureId: 'seed-ful-avl-20260425-home',
    kickoff: '2026-04-25T11:30:00Z',
    homeTeam: 'Fulham',
    awayTeam: 'Aston Villa',
    market: 'home',
    bookmakerOdds: 2.5,
    modelProbability: 0.4319,
    expectedValue: 0.0796,
    confidence: 53.07,
    note: 'Seeded prior pick for tracker foundation',
  },
  {
    fixtureId: 'seed-bre-whu-20260502-away',
    kickoff: '2026-05-02T14:00:00Z',
    homeTeam: 'Brentford',
    awayTeam: 'West Ham United',
    market: 'away',
    bookmakerOdds: 3.75,
    modelProbability: 0.3233,
    expectedValue: 0.2124,
    confidence: 51.87,
    note: 'Seeded prior pick for tracker foundation',
  },
  {
    fixtureId: 'seed-avl-tot-20260503-away',
    kickoff: '2026-05-03T18:00:00Z',
    homeTeam: 'Aston Villa',
    awayTeam: 'Tottenham',
    market: 'away',
    bookmakerOdds: 3.25,
    modelProbability: 0.3484,
    expectedValue: 0.1323,
    confidence: 63.35,
    note: 'Seeded prior pick for tracker foundation',
  },
  {
    fixtureId: 'seed-avl-tot-20260503-over',
    kickoff: '2026-05-03T18:00:00Z',
    homeTeam: 'Aston Villa',
    awayTeam: 'Tottenham',
    market: 'over2_5',
    bookmakerOdds: 1.95,
    modelProbability: 0.5333,
    expectedValue: 0.04,
    confidence: 61.33,
    note: 'Seeded prior pick for tracker foundation',
  },
];

export const trackerSeedResults: TrackerSeedResult[] = [
  {
    fixtureId: 'seed-bou-lee-20260422-away',
    homeGoals: 1,
    awayGoals: 2,
  },
  {
    fixtureId: 'seed-ful-avl-20260425-home',
    homeGoals: 3,
    awayGoals: 1,
  },
  {
    fixtureId: 'seed-bre-whu-20260502-away',
    homeGoals: 2,
    awayGoals: 0,
  },
  {
    fixtureId: 'seed-avl-tot-20260503-away',
    homeGoals: 1,
    awayGoals: 2,
  },
  {
    fixtureId: 'seed-avl-tot-20260503-over',
    homeGoals: 1,
    awayGoals: 2,
  },
];
