import { MatchFixture, OddsLine, TeamProfile } from '@/lib/types';

export const teams: TeamProfile[] = [
  {
    name: 'Arsenal',
    power: 87,
    homeAdvantage: 4,
    awayAdjustment: -1,
    form: 8,
    xgFor: 1.95,
    xgAgainst: 0.92,
    pressing: 8,
    buildUp: 9,
    transition: 7,
    setPieces: 8,
    crossing: 6,
    aerialDefense: 7,
  },
  {
    name: 'Liverpool',
    power: 89,
    homeAdvantage: 4,
    awayAdjustment: -1,
    form: 9,
    xgFor: 2.15,
    xgAgainst: 1.01,
    pressing: 9,
    buildUp: 8,
    transition: 9,
    setPieces: 7,
    crossing: 7,
    aerialDefense: 7,
  },
  {
    name: 'Manchester City',
    power: 91,
    homeAdvantage: 4,
    awayAdjustment: -1,
    form: 7,
    xgFor: 2.05,
    xgAgainst: 0.88,
    pressing: 8,
    buildUp: 10,
    transition: 7,
    setPieces: 7,
    crossing: 6,
    aerialDefense: 8,
  },
  {
    name: 'Newcastle',
    power: 81,
    homeAdvantage: 3,
    awayAdjustment: -1,
    form: 7,
    xgFor: 1.71,
    xgAgainst: 1.18,
    pressing: 8,
    buildUp: 6,
    transition: 8,
    setPieces: 7,
    crossing: 7,
    aerialDefense: 6,
  },
  {
    name: 'Brighton',
    power: 78,
    homeAdvantage: 3,
    awayAdjustment: -1,
    form: 6,
    xgFor: 1.58,
    xgAgainst: 1.34,
    pressing: 7,
    buildUp: 8,
    transition: 7,
    setPieces: 5,
    crossing: 6,
    aerialDefense: 5,
  },
  {
    name: 'Brentford',
    power: 74,
    homeAdvantage: 3,
    awayAdjustment: -1,
    form: 6,
    xgFor: 1.49,
    xgAgainst: 1.41,
    pressing: 6,
    buildUp: 5,
    transition: 8,
    setPieces: 8,
    crossing: 7,
    aerialDefense: 6,
  },
  {
    name: 'Tottenham',
    power: 79,
    homeAdvantage: 3,
    awayAdjustment: -1,
    form: 5,
    xgFor: 1.82,
    xgAgainst: 1.55,
    pressing: 8,
    buildUp: 7,
    transition: 8,
    setPieces: 5,
    crossing: 7,
    aerialDefense: 5,
  },
  {
    name: 'Aston Villa',
    power: 80,
    homeAdvantage: 3,
    awayAdjustment: -1,
    form: 7,
    xgFor: 1.69,
    xgAgainst: 1.21,
    pressing: 7,
    buildUp: 7,
    transition: 7,
    setPieces: 7,
    crossing: 6,
    aerialDefense: 6,
  }
];

export const fixtures: MatchFixture[] = [
  {
    id: 'gw34-ars-bre',
    round: 34,
    kickoff: '2026-04-25T14:00:00Z',
    homeTeam: 'Arsenal',
    awayTeam: 'Brentford',
    daysRestHome: 6,
    daysRestAway: 7,
    injuriesHome: 1,
    injuriesAway: 2,
  },
  {
    id: 'gw34-liv-bha',
    round: 34,
    kickoff: '2026-04-25T16:30:00Z',
    homeTeam: 'Liverpool',
    awayTeam: 'Brighton',
    daysRestHome: 5,
    daysRestAway: 6,
    injuriesHome: 1,
    injuriesAway: 2,
  },
  {
    id: 'gw34-mci-new',
    round: 34,
    kickoff: '2026-04-26T13:00:00Z',
    homeTeam: 'Manchester City',
    awayTeam: 'Newcastle',
    daysRestHome: 4,
    daysRestAway: 7,
    injuriesHome: 2,
    injuriesAway: 1,
  },
  {
    id: 'gw34-tot-avl',
    round: 34,
    kickoff: '2026-04-26T15:30:00Z',
    homeTeam: 'Tottenham',
    awayTeam: 'Aston Villa',
    daysRestHome: 6,
    daysRestAway: 5,
    injuriesHome: 3,
    injuriesAway: 1,
  }
];

export const latestOdds: OddsLine[] = [
  {
    fixtureId: 'gw34-ars-bre',
    bookmaker: 'MockBook',
    home: 1.52,
    draw: 4.35,
    away: 6.7,
    over2_5: 1.74,
    under2_5: 2.12,
    btts_yes: 1.82,
    btts_no: 1.97,
    capturedAt: '2026-04-22T08:00:00Z',
  },
  {
    fixtureId: 'gw34-liv-bha',
    bookmaker: 'MockBook',
    home: 1.7,
    draw: 4.1,
    away: 4.9,
    over2_5: 1.62,
    under2_5: 2.3,
    btts_yes: 1.71,
    btts_no: 2.08,
    capturedAt: '2026-04-22T08:00:00Z',
  },
  {
    fixtureId: 'gw34-mci-new',
    bookmaker: 'MockBook',
    home: 1.88,
    draw: 3.95,
    away: 4.0,
    over2_5: 1.68,
    under2_5: 2.2,
    btts_yes: 1.75,
    btts_no: 2.02,
    capturedAt: '2026-04-22T08:00:00Z',
  },
  {
    fixtureId: 'gw34-tot-avl',
    bookmaker: 'MockBook',
    home: 2.48,
    draw: 3.55,
    away: 2.8,
    over2_5: 1.66,
    under2_5: 2.25,
    btts_yes: 1.63,
    btts_no: 2.22,
    capturedAt: '2026-04-22T08:00:00Z',
  }
];
